### ISSUE TITLE
anticipated Sunday is missing

### ISSUE THREAD

**Issue by peterdiekertz** [DivinumOfficium/divinum-officium#1072] opened 2019-02-16 13:03 UTC
Today, 16 February 2019, should be the anticipated 6th Sunday after Epiphany, in Divino and before.

**Comment by APMarcello3** [comment] 2019-02-16 13:59
Closed by c3febccc7.

**Comment by fiapps** [comment] 2019-02-16 19:02
I think there's still a problem, as a user reported to me and I confirmed: "Terce loads as Sunday VI after Epiphany, but with Saturday Psalms, and ferial chapter and resp brev.  
Sext and None do the same.  Vespers loads correctly as I Vespers of Septuagesima."

https://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=2-16-2019&command=prayTertia&version=Divino%20Afflatu&testmode=regular&lang2=English&votive=

**Comment by fiapps** [comment] 2019-02-16 19:04
Ave Maria!

Since you don't always pay attention to comments on closed issues, I point this out by email as well:

I think there's still a problem, as a user reported to me and I confirmed: "Terce loads as Sunday VI after Epiphany, but with Saturday Psalms, and ferial chapter and resp brev.
Sext and None do the same. Vespers loads correctly as I Vespers of Septuagesima."

https://divinumofficium.com/cgi-bin/horas/Pofficium.pl?date1=2-16-2019&command=prayTertia&version=Divino%20Afflatu&testmode=regular&lang2=English&votive=

I think the issue should be reopened.

**Comment by peterdiekertz** [comment] 2019-02-24 15:07
But I think that is correct, cf. RG IV 4: in ea legantur tres Lectiones de Homilia Dominice, omissis Lectionibus Scriptura: illius Ferie: et in Laudibus dicatur Antiphona ad Benedictus, et Oratio de Dominica xxiii.

It seems to me like only the matins lections and the benedictus antiphona are “affected“ by the anticipation, everything else is still from Saturday.

**Closed** 2019-11-30 20:27 UTC
