### ISSUE TITLE
Lenten Feria celebrated instead of St John of Capistrano (semiduplex) 

### ISSUE THREAD

**Issue by earladrianhans** [DivinumOfficium/divinum-officium#1107] opened 2019-03-28 02:35 UTC
St John of Capistrano should be celebrated today with commemoration of the feria, but instead it's the other way around. I think the issue is that the automated ordo treats Lenten weekdays as actual semidoubles rather than privileged ferias, which shouldn't be the case (because they really aren't semidoubles). They should have their own ranking in the site's calendar

**Comment by igneus** [comment] 2019-03-29 18:23
It should be added that (at least according to the [original report elsewhere](https://www.facebook.com/groups/breviarydiscussion/permalink/2337492252976244/)) the issue is related to **Divino Afflatu** rubrics. Or are other versions affected, too?

**Comment by APMarcello3** [comment] 2019-06-09 16:29
Closed by 89bf3b8.

**Closed by APMarcello3** 2019-06-09 16:29 UTC
