### ISSUE TITLE
Laudes Divinum Afflatu 2/23/16

### ISSUE THREAD

**Issue by glorianyc** [DivinumOfficium/divinum-officium#465] opened 2016-02-23 14:50 UTC
First of all, thank you so very much for the site. Today when I was reading my prayers there was a portion in Latin that I think should have been in English, here it is:

Let us pray.
**Da quaesumus omnipotens Deus: ut beati Matthiae Apostoli tui, quam paevenimus, veneranda solemnitas et devotiones nobis auget ad salutem.**
Through Jesus Christ, thy Son our Lord...

I hope this helps, may our Lord bless this site.

**Comment by rl1234567890** [comment] 2016-02-23 16:13
In the Italian the prayer is present, but everything from the collect of the day to that of the vigil of St. Matthias appears in bold red.

**Comment by mbab** [comment] 2016-02-23 18:24
@glorianyc this is just not translated yet.
On other side there is a bug as St, Mathiae is 25 this year. Look at #443

**Comment by APMarcello3** [comment] 2020-02-24 23:39
Cf. Issue 443

**Comment by gregordick** [comment] 2020-03-29 23:11
The vigil of St Matthias is mishandled in leap years in the placing of its office and Mass, and also in its anticipation in the Martyrology: it ought to be kept on the 24th and anticipated in the Martyrology on the 23rd, but instead it appears on its non-leap-year days of 23rd and 22nd, respectively.

Furthermore, outside of leap years, the vigil ought to be commemorated in the Mass of St Peter Damian on the 23rd, but it is not.  (It is commemorated correctly at Lauds outside of Lent.)

The problems described in the first paragraph are covered by issue #443, but I do not see an issue tracking the problems described in the second paragraph.  Beyond this, I do not see anything in the current issue that is not tracked in issue #443.  @APMarcello3: Is this correct?  If so, I propose to close this issue as being a duplicate of #443 and to begin working on that, and to open a new issue for the non-leap-year commemoration at Mass.

**Comment by APMarcello3** [comment] 2020-04-05 02:50
@gregordick Sounds good to me.

**Closed by APMarcello3** 2020-04-05 02:50 UTC
