### ISSUE TITLE
Vespers of 1st Sunday of Advent, Dec 3, 2023 (DA)

### ISSUE THREAD

**Issue by MRoth1910** [DivinumOfficium/divinum-officium#3418] opened 2023-11-07 21:19 UTC
At Vespers of the 1st Sunday of Advent (Dec. 3, 2023), the commemoration of St Barbara, from I Vespers, is missing.

**Comment by FAJ-Munich** [comment] 2023-11-08 09:36
This is one of those instances, where the current algorithm is just too wrong to be true. I am working on a general fix for all these issues at the moment as also commented on yesterday in the discussion on #3414

**Comment by MRoth1910** [comment] 2023-11-08 17:16
Fair. I wish I could help. (I really don't know anything and can only bring up things as I spot them.)

I did want to return to this: 

> This is one of the instances where DA changed the order by directing the comm. of the concurrent office to come first always: which the algorithm is trying to accomplish but fails to do!

Yes. This is a rubric which I don't understand (and which I've asked about, because I want to give the "why" instead of just pointing out the mistakes.

**Comment by FAJ-Munich** [comment] 2023-11-08 21:34
Let me try to answer to the best of my self-taught understanding (which is sometimes dangerous since I almost failed high school due to my poor grades in Latin 🙈 🤣 )

Comparing the digitally available versions of the Breviarum Romanum 1568, 1888, and 1942, we find three different versions of paragraph 11 of Rubric IX. De Commemorationibus.
The 1888 version is almost identical to 1568 with merely some clarification by the words in bold added:

> Quando contingit fieri plures commemorationes, servetur hic ordo. De Duplici, **licet agatur tamquam Simplex,** fiat ante Dominicam, _&c_

The 1942 version, however, which is claiming to reproduce the Jubilee Version of the Rubrics from 1900, the paragraph reads:

> Quando contingit fieri plures commemorationes, **illæ semper præponantur, quæ ad Officium pertinent, cujuscumque sit ritus; exceptis illis … prout in Rubricis specialibus suo loco dicetur. Deinde** servetur hic ordo: 1 De Dominica privilegiata, 2 de die Octava, _&c_

Now what does "those belonging to the office, always have priority" actually mean? Here I can only guess but it sounds to me it is a Rubric that is to prevent accidental mix up or forgetting of some commemorations when, e.g., in the Sanctorale right next to the prayer of Lauds or Vespers, there is a rubric to commemorate another office. Previously, despite that prayer being available right there on the page, in principal, you first had to think about whether there is a different commemoration that needs to come first requiring extensive page flipping. 

Now, to add insult to injury, Divino Afflatu changed the order of commemorations yet again and the way I interpret Var. & Add. Tit. VII paragraph 5 is that the previously mentioned IX. par. 11 is obsolte then. Apparently that change from 1900 has had a very short half life. 

To explain my understanding of the rubric you have specifically asked for, here is how I read it:

> … cauto quod in Vesperis semper fit prima Commemoratio de Officio concurrenti, _&c_

Let's turn to the example of Vespers of Saturday, October 28, 2023 again:

- The office of Oct 28 is Ss. Simon and Jude, App – Duplex II.  cl. 
- The office of Oct 29 is DNJC Regis – Duplex I. cl. with a commemoratio of the occuring 22nd Sunday after Pentecost.

Therefore, we have 1st Vespers of DNJC Regis. When it comes to the order of commemorations, the concurrent one which is to come first is of 2nd Vespers of Ss. Simon and Jude. All other commemorations, assuming there was not just the Sunday but maybe some other Simplex commemorations that happen to be on a local calendar on Oct 28 and/or 29, come afterwards in the order of priortiy according to the rubrics. In summary, the concurrent office is always the "main" office which is actually said on the previous or the following day. I hope this help (and is correct).

**Comment by MRoth1910** [comment] 2023-11-09 20:35
No, I get it.

It's because this case basically never happens, where a double II class feast is commemorated AND so is a semidouble Sunday.

But it will happen occasionally in October for example.

It's a mess, however.

**Comment by FAJ-Munich** [comment] 2023-11-09 21:53
Well, I wouldn’t say that, in practice, these cases were just as rare as you described. I thought of another example that has happened this year in May: 

On May 3, this year has been Inventione S. Crucis (Duplex II. classis) with the occurrence of In 8va S. Joseph (Duplex majus). At 1st and 2nd Vespers, on the General Calendar, there is concurrence with a Duplex minus feast. Due to the rubric, however, the commemoration of S. Joseph comes after the commemoration of S. Athanasius and S. Monica, respectively, despite its higher rank. 

To make things more complicated, e. g. in the Diocese of Passau, May the 4th is S. Florian (Duplex majus) with a commemoration of S. Monica at both vespers and at Lauds. Therefore, the first commemoration in second vespers on May 3 is of S. Florian followed by S. Joseph **before** S. Monica. That is, because of the other feast, in this diocese the order of commemoration of S. Joseph and S. Monica had to be reversed.

**Comment by MRoth1910** [comment] 2023-11-09 22:19
I think what is confusing me (and probably others who looked at Ss Simon and Jude) is that the concurring office is not Sunday but Christ the King; this is not explicitly said, but it's implied once you see the ordo's instructions. Hence, you then do the commemorations in order of dignity.

The same same applies to the example of May 2 and 3.

**Comment by KPFC** [comment] 2023-11-10 11:45
It happens far more often then one would think, usually in combination with Sundays. July 1st this year comes to my mind (Vespers of Sacred Blood, but then first Com. Visitationis, second Dominicae; which actually follows the order of precedence, but divinumofficium gets it still wrong).
The next time, it will happen on the eve of the first Sunday in Advent: S. Bibiana should be commemorated first, even though she is Semiduplex and Francis Xaver (Dupl. maj.) should be commemorated second, at the moment it is the other way round.

**Comment by MRoth1910** [comment] 2023-11-10 18:19
Well, the first case is different, it seems: Precious Blood is the occurring office and has precedence over both Sundays, period, and the Visitation (which is also the concurring office, since in DA it takes the place of Sundays), whereas in the other cases, the concurring office takes precedence over the office of the calendar day, and the commemorations are made in order of dignity.

The case of St Bibiana is interesting due to the rank being inferior to St Francis Xavier. So there's still something that I'm not understanding (and which the algorithm might not be able to control easily even with some work).

**Comment by KPFC** [comment] 2023-11-10 23:24
The concurrent office is the office, which was said/is about to be said before/after the Vesper in question. The rule in question raises an office, which is actually said and not just commemorated, to the first position with regards to commemorations, notwithstanding its actual liturgical rank. This is why a Semiduplex comes before a Duplex majus: when of the former the office was said, but the latter will be only commemorated, the Semiduplex as the concurrent office gets the first position among the commemorations.

I am not sure how to explain this better.

> Without that special rubric for Vespers, in contrast, the Sunday commemoration would have come first according to order given later in the same rubric.
This is only partially true: the order given in the rubric does not mention Duplex II classis at all. Which makes sense, because it is not necessary: Duplex II cl. feasts can only be transfered, so if they ever get commemorated they are necessarily the concurrent office and are commemorated at the first position after the same rubric. But without that rubric only the Sunday would get commemorated and the Dupl. II cl. would fall below the table ;-)

**Comment by MRoth1910** [comment] 2023-11-11 03:45
> The concurrent office is the office, which was said/is about to be said before/after the Vesper in question. The rule in question raises an office, which is actually said and not just commemorated, to the first position with regards to commemorations, notwithstanding its actual liturgical rank. This is why a Semiduplex comes before a Duplex majus: when of the former the office was said, but the latter will be only commemorated, the Semiduplex as the concurrent office gets the first position among the commemorations.

I have noticed that this happens. But it is **_not_** spelled out. Go see Stercky, vol 1 for yourself.

Most of the time, it works out, particularly on Sundays, even within privileged octaves (the position of said commemoration changes due to the rank), even if one says the commemoration of the following double (major), then goes back to say that of the double commemorated at Lauds, and then to any simples of the following day (therefore departing from the "this then that" rubrics in the breviary.

Where it doesn't work out so cleanly is on Saturdays and at some I Vespers.

It really is more logical based on everything except the ordines of the period to say the Sunday commemoration before Ss Simon and Jude's, or St Francis Xavier before St Bibiana. Or St Damasus before the Octave of the Immaculate Conception (see the calendar for Dec 2022). But it's the other way around.

**Comment by FAJ-Munich** [comment] 2023-11-11 10:01
> The concurrent office is the office, which was said/is about to be said before/after the Vesper in question.

I think this is the most concise explanation I have ever read in English. Thank you!

> It really is more logical based on everything except the ordines of the period to say the Sunday commemoration before Ss Simon and Jude's, or St Francis Xavier before St Bibiana. Or St Damasus before the Octave of the Immaculate Conception (see the calendar for Dec 2022). But it's the other way around.

It is worth to reiterate that this was the case before Divino Afflatu (or at least before the Jubilee Edition 1900 in which the first alteration of the rubric in question seems to have taken place which I do not fully understand.) 
Maybe something worth noting: In the book of 1568 and also the Monastic 1617, even Semiduplex Feasts still enjoyed the right of transference. This is something to be implemented soon too.

**Comment by FAJ-Munich** [comment] 2023-11-27 15:51
@APMarcello3  this issue can be closed as per #3438

**Closed** 2023-11-27 15:53 UTC
